### ISSUE TITLE
Converting Sample Code to ASP.NET Framework

### ISSUE THREAD

**Issue by johancyprich** [BitArmory/ReCaptcha#1]
I'm trying to get the sample code working for a .NET Framework 4.x form. Certain functions are available only for .NET Core. The code below are possible modifications for .NET 4.x:

`

	private string GetIpAddress ()
	{
		string userip = Request.UserHostAddress;

		if (Request.UserHostAddress != null)
		{
			Int64 macinfo = new Int64 ();
			string macSrc = macinfo.ToString ("X");

			if (macSrc == "0")
			{
				if (userip == "127.0.0.1")
					Response.Write ("visited Localhost!");
			}
		}

		return userip;
	}

	private bool ValidateRecaptcha ()
	{
		bool validateResult = true;

		//1. Get the client IP address in your chosen web framework
		//string clientIp = this.HttpContext.Connection.RemoteIpAddress.ToString ();
		// .RemoteIpAddress function not in .NET 4.x, so use GetIpAddress() function.
		string clientIp = GetIpAddress ();
		string token = null;
		string secret = "";

		//2. Extract the `#captcha` field from the hidden HTML form in your chosen web framework
		// .TryGetValue function is not in .NET 4.x. Should we use this.Request.Form["captcha"] instead?
		if (this.Request.Form.TryGetValue ("captcha", out var formField))
		{
			token = formField;
		}

		//3. Validate the reCAPTCHA with Google
		var captchaApi = new ReCaptchaService ();
		//var result = await captchaApi.Verify3Async (token, clientIp, secret);
		// Is it necessary to use await?
		var result = captchaApi.Verify3Async (token, clientIp, secret);

		// result.IsSuccess/.Action/.Score not available in .NET 4.x.
		// BadRequestResult () result not available, but this could just be validateResult=false.
		if (!result.IsSuccess || result.Action != "SOME_ACTION" || result.Score < 0.5)
		{
			// The POST is not valid
			return new BadRequestResult ();
			// validateResult = false;
		}
		else
		{
			//continue processing, everything is okay!
		}

		return validateResult;
	}
`

**Comment by bchavez** [comment]
Hey 	Johan,

Thanks for the sample. Were you able to get the library working in 4.x WebForms?

* Also, what version of the .NET 4.x full framework are you using?

**Comment by johancyprich** [comment]
Hi Brian. I'm using .NET 4.8 on the dev machine and .NET 4.5 on the live server. The site is compiling for .NET 4.5.

I'm looking at the token/result variables on form submit and the values don't look correct. The code to get the "captcha" should be ok, but the problem is the captchaApi.Verify3Async() doesn't seem to be getting right values. So, not sure where I'm going wrong here.

**Comment by bchavez** [comment]
Hi Johan,

Thanks for the info. What does your javascript look like?

For V3 recaptcha, someplace in your webform (or form submission) there should be some code that sets a hidden value in the form that's used to pass to the library for verification.

Here I'm using jQuery:
```
      grecaptcha.ready(function() {
        grecaptcha.execute('GOOGLE_SITE_KEY', {action: 'SOME_ACTION'})
          .then(function(token) {
             // Set `token` in a hidden form input.
             $("#captcha").val(token);
          });
      });
```

What `captchaApi.Verify3Async()` values passed to the method don't look right?

IIRC, `#captcha` the hidden field should ultimately contain something encrypted that looks like the following:
```
93AOLGBMT1l6ZWh_6QffaV5V5NjAQbvr6GOIioQUwwYIfrC-QGKtlZUWxL-AQ_NGlT8hj0NYU6KIS6zTSHNqD-dHH1HGMb6twDIN82awQ73AQj8lDoul0_8osSO1D5-xPn7hQP2uTGNbLp-GNhyUfzOTb0-lVOwNbyMRwt7uooMwUAG4R0G_qbIHj7Ynvu-nwNxbSrIfnjFgCESB-mzhAbpJ8250uQ3l7WjFsxd-CLb1Sy19gqnwUmEJfewcq6X7J1X2OtYXrpwLvVKyMiN9GUcYaJE4AJ9D3s8fzKbGDHeiWPu5CqdBPGQVThvBx6ZoWRq4Y8apF-d_EW
```

**Comment by johancyprich** [comment]
Hi Brian. I set the captcha control to be visible, i.e. 
`<input id="captcha" type="text" name="captcha" value="" />`
and when I execute the form the textbox is empty. I have site keys defined in both sections of the web page and the "grecaptcha.*" code is the same as your example. So not sure where I'm making a mistake here.

**Comment by bchavez** [comment]
Alright, cool. I'll try to whip up a quick example and test it out. I'll report back soon.

**Comment by johancyprich** [comment]
Thanks, that would be great. BTW ... there are no ASP.NET Framework working examples for reCAPTCHA 3 on the internet, so this will be the first.

**Comment by bchavez** [comment]
HI Johan,

I have a demo of a working invisible reCAPTCHA v3 example for **WebForms** and Full .NET Framework v4.8 here: 

https://github.com/BitArmory/ReCaptcha/tree/master/Examples/ReCaptchaV3.WebForms

Feel free to check out the source.

It's possible your `captcha` field is blank because the HTTP submission already took place and the `grecaptcha.execute` didn't fully resolve on the client yet.

Please see the implementation notes on the `default.aspx` page. And don't forget to change the keys in the source if you want to get the demo working:
https://github.com/BitArmory/ReCaptcha/blob/d35e1ae44330d3aff430b9cfe463d4fc154b0c73/Examples/ReCaptchaV3.WebForms/ReCaptchaV3.WebForms/Default.aspx.cs#L10-L14

Let me know if you get it to work or if you have any other questions!

Thanks,
Brian

**Comment by johancyprich** [comment]
Hi Brian. Just to let you know that your asp.net recaptcha is working great. Thanks for your help!

Johan Cyprich



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by bchavez** [comment]
Hi Johan,

Wonderful! Great! Thank you for the update. I'm very happy it's working well for you!

If there's anything else, please feel free to let me know and I'll be happy to help.

:walking_man: :walking_woman: **[Missing Persons - Walking in L.A.](https://www.youtube.com/watch?v=R_UpLtGEWoY)**
