### ISSUE TITLE
Use the global domain recaptcha.net

### ISSUE THREAD

**Issue by Jogai** [BitArmory/ReCaptcha#5]
**Context**

Google.com domains are generally blocked in china, but its easy to use recaptcha globally like google recommends here: https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally

**Alternatives**

No

**Has the feature been requested before?**

No

**If the feature request is approved, would you be willing to submit a PR?**

Yes

**Comment by bchavez** [comment]
Hi @Jogai ,

Thank you for your feature request. I think the ReCaptcha library already contains a constructor to pass in a custom verification URL. See here:

https://github.com/BitArmory/ReCaptcha/blob/master/BitArmory.ReCaptcha/ReCaptchaService.cs#L42-L46

If you use the custom constructor with:
```csharp
var globalUrl = "https://www.recaptcha.net/recaptcha/api/siteverify";
   
var captcha = new BitArmory.ReCaptcha.ReCaptchaService(verifyUrl: globalUrl);
```

Does this solve your problem?

Let me know.

Thanks,
Brian Chavez

**Comment by Jogai** [comment]
Oh thanks, i didnt see that. Problem is that it still loads a js file that has a fixed url to google.com in there. But thats an issue for google then.
