### ISSUE TITLE
Why not using __doPostBack() to submit the form?

### ISSUE THREAD

**Issue by Benjiiim** [BitArmory/ReCaptcha#7]
First of all, thanks a lot for this library.
I have a question regarding the reCaptcha v3 WebForms example.
We can see in the Default.aspx page that a hidden button is used and not the ASP.NET's JavaScript __doPostBack() method.
Is there any specific reason?
Thanks

**Comment by bchavez** [comment]
Hi Benjamin,

No problem! I'm glad you like the library!

Thank you for your question. There's no specific reason I can think of other than a style choice. I think I've generally avoided using `__doPostBack()` in **WebForms** when possible to try to stick with publically documented APIs.

https://stackoverflow.com/questions/5448825/is-it-ok-to-use-dopostback

On the other hand, I guess `__doPostBack()` is so pervasive that it's practically a public API now. This brings back the good ole' **WebForms** memories. :sunglasses: 

I hope that answers your question. If you have any other questions, please feel free to ask after I close the issue!

Thanks,
Brian
